import { Geist, Geist_Mono } from "next/font/google";
import { Hind_Siliguri } from "next/font/google";
import "./globals.css";




const hindSiliguri = Hind_Siliguri({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-hind-siliguri",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased ${hindSiliguri.variable}`}
      >
 {children}
       
      </body>
    </html>
  );
}
